name: NBS Exchange Rate

on:
  push:
    branches:
      - main
      - develop

jobs:
  exchange-rate:
    name: Pack extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      appVersion: ${{ steps.extension-version.outputs.current-version }}
      releaseNotes: ${{ steps.release-notes.outputs.notes }}
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r nbs.zip extension/
      - uses: actions/upload-artifact@v3
        with:
          name: nbs
          path: nbs.zip
      - name: get-version
        id: extension-version
        run: |
          echo "current-version=$(cat ./extension/manifest.json | jq -r '.version')" >> $GITHUB_OUTPUT
      - name: Collect release notes
        id: release-notes
        run: |
          echo "::group::Prepare release notes"
          RELEASE_NOTES=$(awk -v ver=${{ steps.extension-version.outputs.current-version }} '/^## \[/ { if ($2 == "["ver"]") { p=1 } else { p=0 } } p { print }' CHANGELOG.md | tail -n +3)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "::endgroup::"
          echo "notes=${{ env.RELEASE_NOTES }}" >> $GITHUB_OUTPUT
      - name: Create Release Tag
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ github.ref == 'refs/heads/develop' }}
          tag_name: ${{ steps.extension-version.outputs.current-version }}
          body: ${{ env.RELEASE_NOTES }}
  slack-status:
    if: always()
    name: Post Status To Slack
    runs-on: ubuntu-latest
    needs: exchange-rate
    steps:
      - name: Slack Workflow
        id: slack-workflow
        uses: Gamesight/slack-workflow-status@master
        env:
          APP_VERSION: ${{ needs.exchange-rate.outputs.appVersion }}
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: "#project-activity"
          name: "NBS Exchange Rate - Chrome Extension | (v${{ env.APP_VERSION }})"
          icon_emoji: ":euro:"
